### Create a new user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test@test.bg",
    "password": "123456"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given Email
GET http://localhost:3000/auth?email=test@test3.bg

### Update a new user
PATCH http://localhost:3000/auth/21231
content-type: application/json

{
    "email": "test@test.bg",
    "password": "123456"
}

### Delete a particular user with a given ID
DELETE http://localhost:3000/auth/4

### Get the currently singed in user 
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout